name: Testing Python

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./taxoniumtools
      - name: Download files
        run: |
          wget https://github.com/theosanderson/taxonium/raw/master/taxoniumtools/test_data/tfci.meta.tsv.gz
          wget https://raw.githubusercontent.com/theosanderson/taxonium/master/taxoniumtools/test_data/hu1.gb
          wget https://github.com/theosanderson/taxonium/raw/master/taxoniumtools/test_data/tfci.pb
          wget https://github.com/theosanderson/taxonium/raw/master/taxoniumtools/test_data/test_config.json
      - name: Basic test
        run: |
          usher_to_taxonium --input tfci.pb --output tfci-taxonium.jsonl.gz --metadata tfci.meta.tsv.gz --genbank hu1.gb --columns genbank_accession,country,date,pangolin_lineage
      - uses: actions/upload-artifact@v3
        with:
          name: tfci-taxonium
          path: tfci-taxonium.jsonl.gz
      - name: Test with chronumental
        run: |
          pip install chronumental
          usher_to_taxonium --input tfci.pb --output tfci-taxonium-chron.jsonl.gz --metadata tfci.meta.tsv.gz --genbank hu1.gb --columns genbank_accession,country,date,pangolin_lineage --chronumental --chronumental_steps 300
      - uses: actions/upload-artifact@v3
        with:
          name: tfci-taxonium-chron
          path: tfci-taxonium-chron.jsonl.gz
      - name: Test with config
        run: |
          usher_to_taxonium --input tfci.pb --output tfci-taxonium-config.jsonl.gz --metadata tfci.meta.tsv.gz --genbank hu1.gb --columns genbank_accession,country,date,pangolin_lineage --config_json test_config.json
      - uses: actions/upload-artifact@v3
        with:
          name: tfci-taxonium-config
          path: tfci-taxonium-config.jsonl.gz
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Run the scraping script
        run: python .github/selenium/selenium.py

