name: Selenium

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installed package list
        run: apt list --installed
      - uses: actions/download-artifact@v3
        with:
          name: tfci-taxonium-config
          path: ./data/
      - uses: actions/download-artifact@v3
        with:
          name: taxonium_web_client_build
          path: ./web/
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Start server
        run: python -m http.server &
        working-directory: ./web/
      - name: Start server
        run: |
          ls
          python -m http.server 3000 &
        working-directory: ./data/
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Run the selenium script
        run: python .github/selenium_tests/selenium_tests.py "http://localhost:8000/?protoUrl=http://localhost:3000/tfci-taxonium-config.jsonl.gz"
